
PROGRAM GRID_GEN

    USE GEOM_2D_TYPES
	USE GEOM_2D


    CALL READ_INPUT

    NPT = (NYC+1)*(NXC+1)
    NCF = (NYC+1)*(NXC)
    NSI = (NXC-1)*NYC + (NYC-1)*NXC
    NSB = (NXC+NYC)*2
    NSF =  NSI + NSB

   ALLOCATE(IC(NXC,NYC)) !
   ALLOCATE(PT(NPT,2))     ! 1->X-COORD, 2->Y-COORD
   ALLOCATE(TIC(NXC,NYC)) !
   ALLOCATE(TPT(NPT,2)) ! 1-CHI-COORD  , 2->ETA-COORD

   ALLOCATE(CL(NCL))     !
   ALLOCATE(BF(NSF))     !
   ALLOCATE(TCL(NCL))    !
   ALLOCATE(TBF(NSF))    !

   CALL GRID2D_TRASF     ! X-Y COORD TO ---------> CHI-ETA COORD
   CALL WRITE_PLT

END PROGRAM
